# test.sub

universe = vanilla

log = logs/test_$(Cluster).log

# Direct standard output & error streams to files
output = ../logs/interactive_$(Cluster).out
error = ../logs/interactive_$(Cluster).err

# IMPORTANT! Require execute servers that have Staging:
Requirements = (TARGET.HasCHTCStaging == TRUE)

transfer_input_files = utils

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_memory = $(memory)
request_disk = $(disk)

queue
