# testing.sub
universe = vanilla

# IMPORTANT! Require execute servers that have Staging:
Requirements = (Target.HasCHTCStaging == true)

# Specify executable
executable = source/test/testing.sh
# arguments = 

environment = CONDOR_JOB_ID=$(Cluster).$(Process)

# Set files to capture log & standard error stream
log = logs/testing_$(Cluster).log
error = logs/testing_$(Cluster).err

transfer_input_files = utils/

request_cpus = 1
request_disk = $(disk)
request_memory = $(memory)

queue